spring:
  application:
    name: notification-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password:  Welcome@1234
    driver-class-name: org.postgresql.Driver
#    #  datasource:
#        url: jdbc:h2:mem:testdb
#        username: sa
#        password:
#        driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
        group-id: notification-service
        auto-offset-reset: earliest
        max-poll-records: 5   # only 5 messages per poll
        fetch-min-size: 1
        fetch-max-wait: 500
        enable-auto-commit: true
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    #properties:
   #     spring.json.trusted.packages: "*"
#  mail:
#    host: smtp.gmail.com        # or your SMTP host
#    port: 587                   # 465 for SSL, 587 for TLS
#    username: kaushiknandy04@gmail.com
#    password: mzsp bvkx lfxn bobg   # Gmail requires App Password, not your real password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
    mail:
        host: smtp.gmail.com
        username: kaushiknandy04@gmail.com
        password: mzsp bvkx lfxn bobg
        port: 587
        properties:
            mail:
                debug: true
                smtp:
                    auth: false
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                        required: true
                    timeout: 5000
                    writetimeout: 5000
        
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  kafka:
    topic: 
      notification: NOTIFICATION_EVENT

twilio:
  accountSid: AC71684e3e42c88c8efaefb5d5cfbe6ac9
  authToken: 887ca625851b8ed262b2a36b006d8021
  fromNumber: +1 681 254 5959
  whatsappFrom: +14155238886
#file-path-description

#resilience4j.ratelimiter:
#  instances:
#    emailLimiter:
#      limit-for-period: 10   # max 10 emails
#      limit-refresh-period: 1s
#      timeout-duration: 500ms
file:
  upload-dir: "src/main/resources/email-template/"
# spring.mail.* configure for production mail host
server:
  port: 8087
